apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-feed
  labels:
    udagram-app: api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      udagram-app: api-feed
  template:
    metadata:
      labels:
        udagram-app: api-feed
    spec:
      containers:
        - name: api-feed
          image: nguyenhoangvu1996/api_feed
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: postgres-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: postgres-password
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: postgres-host
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: postgres-db
            - name: AWS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: aws-bucket
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: aws-region
            - name: AWS_PROFILE
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: aws-profile
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: jwt-secret
            - name: URL
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: url