apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    run: frontend
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 8100
  selector:
    run: frontend
#  type: LoadBalancer    