apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    udagram-app: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      udagram-app: reverseproxy
  template:
    metadata:
      labels:
        udagram-app: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: nguyenhoangvu1996/reverseproxy
        ports:
        - containerPort: 8080